In [17]:
import numpy as np
import numpy
numpy.__version__

'1.21.6'

In [20]:
import pandas as pd
pd.read_csv('/content/food.csv')

,Food_items,Breakfast,Lunch,Dinner,VegNovVeg,Calories,Fats,Proteins,Iron,Calcium,Sodium,Potassium,Carbohydrates,Fibre,VitaminD,Sugars
0,Asparagus Cooked,0,1,1,,22,0.2,2.4,0.91,23.0,14,224.0,4.1,2.0,0,1.3
1,Avocados,1,0,0,0,160,15.0,2.0,0.55,12.0,7,485.0,8.5,6.7,0,0.7
2,Bananas,1,0,0,0,89,0.3,1.1,0.26,5.0,1,358.0,23.0,2.6,0,12.0
3,Bagels made in wheat,0,1,1,0,250,1.5,10.0,2.76,20.0,439,165.0,49.0,4.1,0,6.1
4,Berries,1,0,0,0,349,0.4,14.0,6.80,190.0,298,77.0,77.0,13.0,0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Vanilla Ice cream,0,0,1,0,207,11.0,3.5,0.09,128.0,80,199.0,24.0,0.7,0,21.0
85,Strawberry Icecream,0,0,1,0,192,8.4,3.2,0.21,120.0,60,188.0,28.0,0.9,0,0.0
86,Marshmallows,0,0,1,0,318,0.2,1.8,0.23,3.0,80,5.0,81.0,0.1,0,58.0
87,Chocolate milk,1,0,0,0,535,30.0,7.7,2.35,189.0,79,372.0,59.0,3.4,0,52.0
88,Rice Pudding,0,0,1,0,376,0.1,2.7,1.79,14.0,366,5.0,91.0,0.7,0,0.0

In [21]:
import pandas as pd
pd.read_csv('/content/nutrition_distriution.csv')

,0Calories,1Fats (gm),2Proteins(g),3Iron(mg),4Calcium(mg),5Sodium(mg),6Potassium(mg),7Carbohydrates (gm),8Fibre (gm),9Vitamin D (mcg),10Sugars (gm)
0,160,15.0,2.0,0.55,12,7,485.0,8.5,6.7,0,0.70
1,89,0.3,1.1,0.26,5,1,358.0,8.5,2.6,0,12.00
2,349,0.4,14.0,6.80,190,298,77.0,8.5,13.0,0,46.00
3,331,24.0,20.0,0.84,497,966,363.0,8.5,0.0,0,0.00
4,2,0.0,0.3,0.02,2,1,50.0,8.5,0.0,0,0.00
5,97,1.4,3.3,0.55,2,253,3.3,8.5,2.7,0,7.70
6,93,2.1,5.6,2.63,2,9,272.0,8.5,11.0,0,6.30
7,97,6.9,3.8,0.12,2,52,178.0,8.5,0.0,0,0.00
8,553,44.0,18.0,6.68,2,12,660.0,8.5,3.3,0,5.90
9,97,0.2,1.5,0.80,2,3,212.0,8.5,11.0,0,0.00
10,57,0.1,0.4,0.18,2,1,116.0,8.5,3.1,0,9.80
11,411,17.0,46.0,8.57,2,329,1129.0,8.5,7.1,200,5.70
12,381,1.4,2.0,0.80,2,286,110.0,8.5,2.5,0,65.00
13,429,9.5,13.0,2.28,2,490,241.0,8.5,14.0,0,0.50
14,168,3.7,4.5,8.00,2,94,76.0,8.5,0.9,0,0.10
15,156,1.7,5.0,17.20,2,207,63.0,8.5,2.1,0,0.74
16,130,1.5,2.6,3.16,2,201,117.0,8.5,1.1,0,0.50
17,16,0.2,1.2,0.47,2,42,212.0,8.5,0.9,0,2.63
18,60,4.0,3.1,0.08,2,70,234.0,8.5,0.0,1,7.00
19,407,6.2,4.4,3.81,2,457,51.0,8.5,2.9,0,55.00
20,188,7.2,4.4,24.00,2,522,91.0,8.5,2.2,0,0.24
21,151,2.4,9.0,37.40,2,438,180.0,8.5,1.0,0,1.35
22,579,50.0,21.0,3.71,2,1,733.0,8.5,13.0,0,4.40
23,22,0.3,3.1,0.50,2,5,318.0,8.5,1.0,7,2.00
24,196,15.0,14.0,1.89,2,207,152.0,8.5,0.0,88,0.40
25,76,0.1,1.4,0.72,2,27,230.0,8.5,2.5,0,5.70
26,87,0.1,1.9,0.31,2,240,379.0,8.5,2.0,0,0.90
27,45,0.2,0.7,0.20,2,1,200.0,8.5,0.2,0,8.40
28,73,1.9,10.0,0.04,2,34,141.0,8.5,0.0,0,3.60
29,40,0.9,3.2,0.88,2,1,92.0,8.5,2.6,0,0.00
30,1,0.0,0.2,0.02,2,1,0.2,8.5,0.0,0,0.00
31,486,31.0,17.0,7.72,2,16,407.0,8.5,34.0,0,0.00
32,384,0.9,5.9,19.40,2,571,107.0,8.5,2.7,286,7.80
33,1,0.0,0.0,0.08,2,1,9.0,8.5,0.0,0,0.00
34,52,0.2,0.3,0.12,2,1,107.0,8.5,24.0,0,10.00
35,32,0.3,0.7,0.41,2,1,153.0,8.5,2.0,0,4.90
36,120,1.9,4.4,1.49,2,7,172.0,8.5,2.8,0,0.90
37,350,22.0,4.3,0.75,2,313,362.0,8.5,3.2,0,2.20
38,550,50.0,22.0,3.40,2,1531,257.0,8.5,0.0,0,0.00
39,519,34.0,2.3,1.25,2,6,536.0,8.5,7.7,0,35.00
40,304,0.0,0.3,0.42,2,4,52.0,8.5,0.2,0,82.00
41,535,30.0,7.7,2.35,2,79,372.0,8.5,3.4,0,52.00

In [22]:
pip install tk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tk
  Downloading tk-0.1.0-py3-none-any.whl (3.9 kB)
Installing collected packages: tk
Successfully installed tk-0.1.0

In [23]:
from tkinter import *
import tkinter as tk

In [24]:
from PIL import ImageFilter,Image

In [25]:
import numpy as np
 
from collections import defaultdict
from sklearn.cluster import KMeans

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import nltk
from nltk.stem.lancaster import LancasterStemmer
stemmer = LancasterStemmer()

In [46]:
import pickle
import numpy as np
from keras.models import load_model
model = load_model('model.h5')
import json
import random
intents = json.loads(open('intents2.json').read())
words = pickle.load(open('words.pkl','rb'))
labels = pickle.load(open('labels.pkl','rb'))

In [47]:
data=pd.read_csv('food.csv')
Breakfastdata=data['Breakfast']
BreakfastdataNumpy=Breakfastdata.to_numpy()

In [48]:
Lunchdata=data['Lunch']
LunchdataNumpy=Lunchdata.to_numpy()

In [78]:
Dinnerdata=data['Dinner']
DinnerdataNumpy=Dinnerdata.to_numpy()
Food_itemsdata=data['Food_items']

In [102]:
def show_entry_fields():
 print("\n Age: %s\n Veg-NonVeg: %s\n Weight: %s kg\n Hight: %s cm\n"(e1.get(),e2.get(),e3.get(),e4.get()))
def Weight_Loss():
  show_entry_fields()
breakfastfoodseparated=[]
Lunchfoodseparated=[]
Dinnerfoodseparated=[]
breakfastfoodseparatedID=[]
LunchfoodseparatedID=[]
DinnerfoodseparatedID=[]
for i in range(len(Breakfastdata)):
  if BreakfastdataNumpy[i]==1:
    breakfastfoodseparated.append( Food_itemsdata[i] )
    breakfastfoodseparatedID.append(i)
  if LunchdataNumpy[i]==1:
    Lunchfoodseparated.append(Food_itemsdata[i])
    LunchfoodseparatedID.append(i)
  if DinnerdataNumpy[i]==1:
    Dinnerfoodseparated.append(Food_itemsdata[i])
    DinnerfoodseparatedID.append(i)

In [96]:
LunchfoodseparatedIDdata = data.iloc[LunchfoodseparatedID]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T
val=list(np.arange(5,15))
Valapnd=[0]+val
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.iloc[Valapnd]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T
Valapnd=[0]+val
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.iloc[Valapnd]
LunchfoodseparatedIDdata=LunchfoodseparatedIDdata.T
#print(LunchfoodseparatedIDdata)

In [101]:
# retrieving Breafast data rows by loc method
breakfastfoodseparatedIDdata = data.iloc[breakfastfoodseparatedID]
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.T
val=list(np.arange(5,15))
Valapnd=[0]+val
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.iloc[Valapnd]
breakfastfoodseparatedIDdata=breakfastfoodseparatedIDdata.T